apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: multi-cluster
  region: ap-south-1

nodeGroups:
  - name: free-tier-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    amiFamily: AmazonLinux2

addons:
  - name: aws-ebs-csi-driver
