name: Deploy MultiK8s

on:
  push:
    branches:
      - feature/* # Trigger build for feature branches
      - master    # Trigger build and deploy when code is pushed to master
  pull_request:
    branches:
      - master # Trigger build when PR is merged into master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Repository Files in build
        run: ls -R         

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t mukkipandy/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true mukkipandy/react-test npm test

      - name: Build
        run: |-
          docker build -t mukkipandy/multi-client-k8s-gh:latest -t mukkipandy/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t mukkipandy/multi-server-k8s-gh:latest -t mukkipandy/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t mukkipandy/multi-worker-k8s-gh:latest -t mukkipandy/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        if: success()
        run: |-
          docker push mukkipandy/multi-client-k8s-gh:latest
          docker push mukkipandy/multi-server-k8s-gh:latest
          docker push mukkipandy/multi-worker-k8s-gh:latest

          docker push mukkipandy/multi-client-k8s-gh:${{ env.SHA }}
          docker push mukkipandy/multi-server-k8s-gh:${{ env.SHA }}
          docker push mukkipandy/multi-worker-k8s-gh:${{ env.SHA }}     

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' && success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: 'k8s/'

      - name: List Repository Files in deployment
        run: ls -R 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Debug Kubernetes Config
        run: kubectl config view

      - name: Update Kubeconfig
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name multi-cluster

      - name: Debug Kubernetes Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get storageclass

      - name: Clean Up Old Resources
        run: |
          kubectl delete deployments,services,ingress,pvc,configmap -l app=multi-app || true

      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

      - name: Wait for NGINX Ingress Controller to Be Ready
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=Available deployment/ingress-nginx-controller \
            --timeout=180s

      - name: Deploy to EKS
        run: |-
          kubectl apply -f k8s --validate=false
          kubectl set image deployments/server-deployment server=mukkipandy/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=mukkipandy/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=mukkipandy/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Wait for Deployment to Stabilize
        run: |
          echo "Waiting for pods to stabilize..."
          sleep 30

      - name: Verify Pod Status
        run: |
          kubectl get pods --all-namespaces

      - name: Verify Ingress
        run: |
          kubectl get ingress
          kubectl describe ingress ingress-service

      - name: Verify Application Health
        run: |
          kubectl rollout status deployment/server-deployment
          kubectl rollout status deployment/client-deployment
          kubectl rollout status deployment/worker-deployment       